version : '3.8'

services :
 api:
  build :
   context: ./api
   dockerfile: Dockerfile
  ports :
   -"5000:5000"
  networks:
   -ntx-network
 etl:
  build:
   contect: ./etl
   dockerfile: Dockerfile
  depends_on:
   - api
  networks:
   - ntx-networks
networks:
 ntx-network:
  driver: bridge
